### PR TITLE
Set up fresh project

### LINKED ISSUE #51: Set up fresh CubeIDE project
For developers to implement features, an empty project should be created for developers to work on.

### LINKED ISSUE #54: [Task]: Setup start project to git
### Parent Backlog Item

#51

### Description of new task

A blank cubeMX project shall be uploaded to git to allow others to work from.

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

### PR DESCRIPTION
**Pull request by ljungqvistaxel**
Project name is _battery_management_system_, and a .gitignore is already in the project folder.

Closes #51 
Closes #54

### CODE REVIEW

**Review by ViktorM02 — CHANGES_REQUESTED** [review]
The history doesn't look right

**Comment by ljungqvistaxel** [comment]
@ViktorM02 Fixed history by branching from dev instead of main. (why did I do that?)

**Review by ViktorM02 — DISMISSED** [review]

**Comment by ljungqvistaxel** [comment]
Someone should test that the project opens and builds on their computer. Can you do this @KevFord ?

**Review by KevFord — APPROVED** [review]
Builds fine on my computer

**Pull request merged**
